id: P727D67DF
initial_creation_type: input
source_metadata:
  title: Tsultrim Zangpo
  language: bo
  description: 'A series of texts by and about Tulku Tsultrim Zangpo (sprul sku tshul
    khrims bzang po, 1884–c.1957) alias Tulku Tsullo (sprul sku tshul lo) of Shukjung
    Monastery:'
  volume:
    e6712cae507d495ba01605ccd83928cd:
      title: A Torch to Illuminate Crucial Points of the Path of Meditation
      parent: Dzogchen
    30a92000775a4c20b5a1280743c4af47:
      title: The Four Uncommon Samayas of the Great Perfection
      parent: Dzogchen
    e3fc7ee7d54748d68828b730d6f24650:
      title: A Simple Practice of Phowa, 'Transference of Consciousness'
      parent: Phowa
    b6494d14cc664286ab9eb57bb27143b0:
      title: 'A Shower of Blessings: A Sādhana of Blue-Green Tārā'
      parent: Sādhanas
created_at: '2022-03-01T01:56:58.994914'
last_modified_at: '2022-03-01T01:56:58.994917'
statistics:
  total_words: 2610
  total_non_words: 257
quality:
  non_words_ratio: 0.1
